export interface MarketConfig {
  id: string;
  countryNameEn: string;
  countries: string[];
  edition: string;
  cities: string;
  placeholder: string;
  solarDeclination: string;
  currencySymbol: string;
  defaults: {
    electricityPrice: number;
    feedInPrice: number;
    installCostPerKwp: number;
    selfConsumptionRatio: number;
  };
  ranges: {
    electricityPrice: { min: number; max: number; step: number };
    feedInPrice: { min: number; max: number; step: number };
    installCostPerKwp: { min: number; max: number; step: number };
  };
  locale: string;
  t: {
    kicker: string;
    headline1: string;
    headline2: string;
    body: string;
    pressEnter: string;
    trust1title: string;
    trust1body: string;
    trust2title: string;
    trust2body: string;
    trust3title: string;
    trust3body: string;
    property: string;
    scanningRoof: string;
    noData: string;
    noCoverage: string;
    tryAnother: string;
    disclaimer: string;
    systemSize: string;
    panel: string;
    panels: string;
    max: string;
    adjustAssumptions: string;
    electricityPrice: string;
    feedInPrice: string;
    installCost: string;
    selfConsumption: string;
    calculating: string;
    annualProduction: string;
    kwhPerYear: string;
    yearOneSavings: string;
    systemCost: string;
    payback: string;
    years: string;
    over25yr: string;
    lifetimeGain: string;
    co2Offset: string;
  };
}

export const atMarket: MarketConfig = {
  id: "at",
  countryNameEn: "Austria",
  countries: ["at"],
  edition: "Österreich-Edition",
  cities: "Wien · Graz · Linz · Salzburg",
  placeholder: "Mariahilfer Straße 1, Wien…",
  solarDeclination: "SOLARE DEKLINATION · 47°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.27,
    feedInPrice: 0.06,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "de-AT",
  t: {
    kicker: "№ 01 — Ihre Sonnenkarte",
    headline1: "Wie viel Sonne",
    headline2: "bekommt Ihr Dach?",
    body: "Geben Sie Ihre österreichische Adresse ein. Wir vermessen Ihr Dach per Satellit, platzieren Module dort, wo sie am meisten bringen, und zeigen, was Sie in 25 Jahren sparen.",
    pressEnter: "↵ nach Auswahl bestätigen",
    trust1title: "Satellitenvermessung",
    trust1body: "Dachfläche, Neigung, Ausrichtung und Verschattung per Google Solar API.",
    trust2title: "Österreichische Tarife",
    trust2body: "Aktuelle Strompreise, OeMAG-Einspeisetarif und regionale Installationskosten.",
    trust3title: "Zertifizierte Installateure",
    trust3body: "Angebote von zertifizierten österreichischen Photovoltaik-Fachbetrieben.",
    property: "Objekt",
    scanningRoof: "Dachdaten werden geladen…",
    noData: "Keine Daten verfügbar.",
    noCoverage: "Für diese Adresse liegen noch keine Satelliten-Solardaten vor. Versuchen Sie eine nahe gelegene Adresse.",
    tryAnother: "Andere Adresse versuchen",
    disclaimer: "Schätzungen basieren auf Google Solar API und typischen österreichischen Tarifen. Ein zertifizierter Installateur erstellt nach einer Vor-Ort-Besichtigung ein verbindliches Angebot.",
    systemSize: "Systemgröße",
    panel: "Modul",
    panels: "Module",
    max: "max",
    adjustAssumptions: "Annahmen anpassen",
    electricityPrice: "Strompreis",
    feedInPrice: "Einspeisetarif",
    installCost: "Installationskosten",
    selfConsumption: "Eigenverbrauch",
    calculating: "Berechnung…",
    annualProduction: "Jahresertrag",
    kwhPerYear: "kWh/Jahr",
    yearOneSavings: "Ersparnisse Jahr 1",
    systemCost: "Systemkosten",
    payback: "Amortisation",
    years: "Jahre",
    over25yr: "> 25 J.",
    lifetimeGain: "25-Jahre-Ertrag",
    co2Offset: "CO₂-Einsparung/Jahr",
  },
};

export const beMarket: MarketConfig = {
  id: "be",
  countryNameEn: "Belgium",
  countries: ["be"],
  edition: "Belgische editie",
  cities: "Brussel · Antwerpen · Gent · Luik",
  placeholder: "Grote Markt 1, Brussel…",
  solarDeclination: "ZONSDECLINATIE · 51°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.29,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "nl-BE",
  t: {
    kicker: "№ 01 — Uw nieuwe zonnekaart",
    headline1: "Hoeveel zon",
    headline2: "krijgt uw dak?",
    body: "Voer een Belgisch adres in. We meten uw dak via satelliet, plaatsen panelen waar ze het meest opleveren en laten u zien hoeveel u in vijfentwintig jaar bespaart.",
    pressEnter: "Druk op ↵ na het selecteren van een suggestie",
    trust1title: "Satellietmeting",
    trust1body: "Dakoppervlak, helling, oriëntatie en schaduw via Google Solar API.",
    trust2title: "Belgische tarieven",
    trust2body: "Actuele energieprijzen, prosumententarief en installatiekosten voor België.",
    trust3title: "Gecertificeerde installateurs",
    trust3body: "Offertes van Synergrid-erkende installateurs, geen callcenters.",
    property: "Woning",
    scanningRoof: "Dakgegevens laden…",
    noData: "Geen gegevens beschikbaar.",
    noCoverage: "Dit adres valt nog niet onder satelliet-zonnedata. Probeer een naburig adres of een andere wijk.",
    tryAnother: "Ander adres proberen",
    disclaimer: "Schattingen zijn gebaseerd op Google Solar API en typische Belgische tarieven. Een erkende installateur geeft na een plaatsbezoek een bindende offerte.",
    systemSize: "Systeemgrootte",
    panel: "paneel",
    panels: "panelen",
    max: "max",
    adjustAssumptions: "Aannames aanpassen",
    electricityPrice: "Elektriciteitsprijs",
    feedInPrice: "Injectietarief",
    installCost: "Installatiekosten",
    selfConsumption: "Eigenverbruik",
    calculating: "Berekenen…",
    annualProduction: "Jaarproductie",
    kwhPerYear: "kWh/jaar",
    yearOneSavings: "Besparing jaar 1",
    systemCost: "Systeemkosten",
    payback: "Terugverdientijd",
    years: "jaar",
    over25yr: "> 25 jr",
    lifetimeGain: "Netto winst 25 jaar",
    co2Offset: "CO₂-reductie/jaar",
  },
};

export const bgMarket: MarketConfig = {
  id: "bg",
  countryNameEn: "Bulgaria",
  countries: ["bg"],
  edition: "България издание",
  cities: "София · Пловдив · Варна · Бургас",
  placeholder: "бул. Витоша 1, София…",
  solarDeclination: "СЛЪНЧЕВА ДЕКЛИНАЦИЯ · 43°N",
  currencySymbol: "лв",
  defaults: {
    electricityPrice: 0.14,
    feedInPrice: 0.04,
    installCostPerKwp: 2000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.50, step: 0.01 },
    feedInPrice: { min: 0, max: 0.20, step: 0.01 },
    installCostPerKwp: { min: 800, max: 2000, step: 100 },
  },
  locale: "bg-BG",
  t: {
    kicker: "№ 01 — Слънчевата ви карта",
    headline1: "Колко слънце",
    headline2: "получава покривът ви?",
    body: "Въведете български адрес. Ще измерим покрива ви от сателит, ще наредим панелите там, където дават най-много, и ще ви покажем спестяванията за 25 години.",
    pressEnter: "Натиснете ↵ след избор на предложение",
    trust1title: "Сателитно измерване",
    trust1body: "Площ, наклон, ориентация и засенчване на покрива чрез Google Solar API.",
    trust2title: "Български тарифи",
    trust2body: "Актуални цени на ток, преференциална изкупна цена и разходи за монтаж в България.",
    trust3title: "Сертифицирани монтажници",
    trust3body: "Оферти от лицензирани монтажници в България, а не от кол центрове.",
    property: "Имот",
    scanningRoof: "Зареждане на данни за покрива…",
    noData: "Няма налични данни.",
    noCoverage: "Този адрес все още не е покрит от сателитни слънчеви данни. Опитайте близък адрес.",
    tryAnother: "Опитайте друг адрес",
    disclaimer: "Оценките се базират на Google Solar API и типични български тарифи. Лицензиран монтажник ще предостави обвързваща оферта след оглед на място.",
    systemSize: "Размер на системата",
    panel: "панел",
    panels: "панела",
    max: "макс",
    adjustAssumptions: "Промяна на параметрите",
    electricityPrice: "Цена на тока",
    feedInPrice: "Изкупна цена",
    installCost: "Разходи за монтаж",
    selfConsumption: "Собствено потребление",
    calculating: "Изчисляване…",
    annualProduction: "Годишно производство",
    kwhPerYear: "kWh/год",
    yearOneSavings: "Спестявания година 1",
    systemCost: "Цена на системата",
    payback: "Изплащане",
    years: "години",
    over25yr: "> 25 год.",
    lifetimeGain: "Нетна печалба 25 год.",
    co2Offset: "CO₂ намаление/год.",
  },
};

export const chMarket: MarketConfig = {
  id: "ch",
  countryNameEn: "Switzerland",
  countries: ["ch"],
  edition: "Schweizer Edition",
  cities: "Zürich · Bern · Basel · Genf",
  placeholder: "Bahnhofstrasse 1, Zürich…",
  solarDeclination: "SOLARE DEKLINATION · 47°N",
  currencySymbol: "CHF",
  defaults: {
    electricityPrice: 0.27,
    feedInPrice: 0.06,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.10, max: 0.80, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 500, max: 1000, step: 50 },
  },
  locale: "de-CH",
  t: {
    kicker: "№ 01 — Ihre Sonnenkarte",
    headline1: "Wie viel Sonne",
    headline2: "bekommt Ihr Dach?",
    body: "Geben Sie Ihre Schweizer Adresse ein. Wir vermessen Ihr Dach per Satellit, platzieren Module optimal und zeigen, was Sie in 25 Jahren sparen.",
    pressEnter: "↵ nach Auswahl bestätigen",
    trust1title: "Satellitenvermessung",
    trust1body: "Dachfläche, Neigung, Ausrichtung und Verschattung per Google Solar API.",
    trust2title: "Schweizer Vergütung",
    trust2body: "Einmalvergütung (EIV/KEV), lokale Stromtarife und aktuelle Installationskosten für die Schweiz.",
    trust3title: "Zertifizierte Installateure",
    trust3body: "Angebote von Suissetec-zertifizierten Photovoltaik-Fachbetrieben.",
    property: "Objekt",
    scanningRoof: "Dachdaten werden geladen…",
    noData: "Keine Daten verfügbar.",
    noCoverage: "Für diese Adresse liegen noch keine Satelliten-Solardaten vor. Versuchen Sie eine nahe gelegene Adresse.",
    tryAnother: "Andere Adresse versuchen",
    disclaimer: "Schätzungen basieren auf Google Solar API und typischen Schweizer Tarifen. Ein Suissetec-zertifizierter Installateur erstellt nach einer Vor-Ort-Besichtigung ein verbindliches Angebot.",
    systemSize: "Systemgrösse",
    panel: "Modul",
    panels: "Module",
    max: "max",
    adjustAssumptions: "Annahmen anpassen",
    electricityPrice: "Strompreis",
    feedInPrice: "Einspeisevergütung",
    installCost: "Installationskosten",
    selfConsumption: "Eigenverbrauch",
    calculating: "Berechnung…",
    annualProduction: "Jahresertrag",
    kwhPerYear: "kWh/Jahr",
    yearOneSavings: "Ersparnisse Jahr 1",
    systemCost: "Systemkosten",
    payback: "Amortisation",
    years: "Jahre",
    over25yr: "> 25 J.",
    lifetimeGain: "25-Jahre-Ertrag",
    co2Offset: "CO₂-Einsparung/Jahr",
  },
};

export const cyMarket: MarketConfig = {
  id: "cy",
  countryNameEn: "Cyprus",
  countries: ["cy"],
  edition: "Έκδοση Κύπρου",
  cities: "Λευκωσία · Λεμεσός · Λάρνακα · Πάφος",
  placeholder: "Λεωφόρος Αρχιεπισκόπου Μακαρίου 1, Λευκωσία…",
  solarDeclination: "ΗΛΙΑΚΗ ΑΠΟΚΛΙΣΗ · 35°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.24,
    feedInPrice: 0.08,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.60,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "el-CY",
  t: {
    kicker: "№ 01 — Ο ηλιακός χάρτης σας",
    headline1: "Πόσο ήλιο δέχεται",
    headline2: "η στέγη σας;",
    body: "Πληκτρολογήστε μια κυπριακή διεύθυνση. Θα μετρήσουμε τη στέγη σας από δορυφόρο, θα τοποθετήσουμε πάνελ εκεί που αποδίδουν περισσότερο και θα σας δείξουμε τις εξοικονομήσεις σε 25 χρόνια.",
    pressEnter: "Πατήστε ↵ αφού επιλέξετε πρόταση",
    trust1title: "Δορυφορική μέτρηση",
    trust1body: "Εμβαδόν, κλίση, προσανατολισμός και σκίαση στέγης μέσω Google Solar API.",
    trust2title: "Κυπριακά τιμολόγια",
    trust2body: "Τρέχουσες τιμές ηλεκτρισμού, τιμή net metering ΑΗΚ και κόστος εγκατάστασης.",
    trust3title: "Πιστοποιημένοι εγκαταστάτες",
    trust3body: "Προσφορές από εγκεκριμένους εγκαταστάτες φωτοβολταϊκών στην Κύπρο.",
    property: "Ακίνητο",
    scanningRoof: "Φόρτωση δεδομένων στέγης…",
    noData: "Δεν υπάρχουν διαθέσιμα δεδομένα.",
    noCoverage: "Αυτή η διεύθυνση δεν καλύπτεται ακόμα από δορυφορικά ηλιακά δεδομένα. Δοκιμάστε μια κοντινή διεύθυνση.",
    tryAnother: "Δοκιμάστε άλλη διεύθυνση",
    disclaimer: "Οι εκτιμήσεις βασίζονται στο Google Solar API και σε τυπικά κυπριακά τιμολόγια. Πιστοποιημένος εγκαταστάτης θα παρέχει δεσμευτική προσφορά μετά από επιτόπια επίσκεψη.",
    systemSize: "Μέγεθος συστήματος",
    panel: "πάνελ",
    panels: "πάνελ",
    max: "μέγ",
    adjustAssumptions: "Προσαρμογή παραδοχών",
    electricityPrice: "Τιμή ηλεκτρισμού",
    feedInPrice: "Τιμή net metering",
    installCost: "Κόστος εγκατάστασης",
    selfConsumption: "Αυτοκατανάλωση",
    calculating: "Υπολογισμός…",
    annualProduction: "Ετήσια παραγωγή",
    kwhPerYear: "kWh/έτος",
    yearOneSavings: "Εξοικονόμηση έτους 1",
    systemCost: "Κόστος συστήματος",
    payback: "Απόσβεση",
    years: "χρόνια",
    over25yr: "> 25 χρ.",
    lifetimeGain: "Καθαρό κέρδος 25 ετών",
    co2Offset: "Μείωση CO₂/έτος",
  },
};

export const czMarket: MarketConfig = {
  id: "cz",
  countryNameEn: "Czechia",
  countries: ["cz"],
  edition: "Česká edice",
  cities: "Praha · Brno · Ostrava · Plzeň",
  placeholder: "Václavské náměstí 1, Praha…",
  solarDeclination: "SLUNEČNÍ DEKLINACE · 50°N",
  currencySymbol: "Kč",
  defaults: {
    electricityPrice: 5.50,
    feedInPrice: 1.50,
    installCostPerKwp: 25000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 1, max: 15, step: 0.25 },
    feedInPrice: { min: 0, max: 5, step: 0.25 },
    installCostPerKwp: { min: 10000, max: 25000, step: 1000 },
  },
  locale: "cs-CZ",
  t: {
    kicker: "№ 01 — Vaše sluneční mapa",
    headline1: "Kolik slunce dopadá",
    headline2: "na vaši střechu?",
    body: "Zadejte českou adresu. Změříme vaši střechu ze satelitu, umístíme panely tam, kde vydělají nejvíc, a ukážeme vám úspory za pětadvacet let.",
    pressEnter: "Po výběru návrhu stiskněte ↵",
    trust1title: "Satelitní měření",
    trust1body: "Plocha, sklon, orientace a zastínění střechy přes Google Solar API.",
    trust2title: "České tarify",
    trust2body: "Aktuální ceny elektřiny, výkupní cena ERÚ a náklady na instalaci v ČR.",
    trust3title: "Certifikovaní instalatéři",
    trust3body: "Nabídky od certifikovaných instalatérů fotovoltaiky, ne call center.",
    property: "Nemovitost",
    scanningRoof: "Načítání dat střechy…",
    noData: "Žádná data nejsou k dispozici.",
    noCoverage: "Tato adresa zatím není pokryta satelitními slunečními daty. Zkuste blízkou adresu nebo jinou ulici.",
    tryAnother: "Zkusit jinou adresu",
    disclaimer: "Odhady jsou založeny na Google Solar API a typických českých tarifech. Certifikovaný instalatér poskytne závaznou nabídku po místní prohlídce.",
    systemSize: "Velikost systému",
    panel: "panel",
    panels: "panelů",
    max: "max",
    adjustAssumptions: "Upravit předpoklady",
    electricityPrice: "Cena elektřiny",
    feedInPrice: "Výkupní cena",
    installCost: "Náklady na instalaci",
    selfConsumption: "Vlastní spotřeba",
    calculating: "Výpočet…",
    annualProduction: "Roční výroba",
    kwhPerYear: "kWh/rok",
    yearOneSavings: "Úspory rok 1",
    systemCost: "Cena systému",
    payback: "Návratnost",
    years: "let",
    over25yr: "> 25 let",
    lifetimeGain: "Čistý zisk za 25 let",
    co2Offset: "Úspora CO₂/rok",
  },
};

export const deMarket: MarketConfig = {
  id: "de",
  countryNameEn: "Germany",
  countries: ["de"],
  edition: "Deutschland-Edition",
  cities: "Berlin · Hamburg · München · Köln",
  placeholder: "Unter den Linden 1, Berlin…",
  solarDeclination: "SOLARE DEKLINATION · 51°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.39,
    feedInPrice: 0.08,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "de-DE",
  t: {
    kicker: "№ 01 — Neue Sonnenkarte",
    headline1: "Wie viel Sonne",
    headline2: "bekommt Ihr Dach?",
    body: "Geben Sie Ihre Adresse ein. Wir vermessen Ihr Dach per Satellit, platzieren Module optimal und zeigen, was Sie in 25 Jahren sparen.",
    pressEnter: "↵ nach Auswahl bestätigen",
    trust1title: "Satellitenvermessung",
    trust1body: "Dachfläche, Neigung, Ausrichtung und Verschattung per Google Solar API.",
    trust2title: "EEG-Einspeisetarif",
    trust2body: "Aktuelle Strompreise, MFR-Einspeisevergütung nach EEG und Installationskosten für Deutschland.",
    trust3title: "Zertifizierte Installateure",
    trust3body: "Angebote von zertifizierten deutschen PV-Fachbetrieben – kein Callcenter.",
    property: "Objekt",
    scanningRoof: "Dachdaten werden geladen…",
    noData: "Keine Daten verfügbar.",
    noCoverage: "Für diese Adresse liegen noch keine Satelliten-Solardaten vor. Versuchen Sie eine nahe gelegene Adresse.",
    tryAnother: "Andere Adresse versuchen",
    disclaimer: "Schätzungen basieren auf Google Solar API und typischen deutschen Tarifen. Ein zertifizierter Installateur erstellt nach einer Vor-Ort-Besichtigung ein verbindliches Angebot.",
    systemSize: "Systemgröße",
    panel: "Modul",
    panels: "Module",
    max: "max",
    adjustAssumptions: "Annahmen anpassen",
    electricityPrice: "Strompreis",
    feedInPrice: "Einspeisevergütung",
    installCost: "Installationskosten",
    selfConsumption: "Eigenverbrauch",
    calculating: "Berechnung…",
    annualProduction: "Jahresertrag",
    kwhPerYear: "kWh/Jahr",
    yearOneSavings: "Ersparnisse Jahr 1",
    systemCost: "Systemkosten",
    payback: "Amortisation",
    years: "Jahre",
    over25yr: "> 25 J.",
    lifetimeGain: "25-Jahre-Ertrag",
    co2Offset: "CO₂-Einsparung/Jahr",
  },
};

export const dkMarket: MarketConfig = {
  id: "dk",
  countryNameEn: "Denmark",
  countries: ["dk"],
  edition: "Dansk udgave",
  cities: "København · Aarhus · Odense · Aalborg",
  placeholder: "Strøget 1, København…",
  solarDeclination: "SOLARDEKLINATION · 56°N",
  currencySymbol: "kr",
  defaults: {
    electricityPrice: 3.50,
    feedInPrice: 0.80,
    installCostPerKwp: 7500,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 1, max: 6, step: 0.10 },
    feedInPrice: { min: 0, max: 2, step: 0.05 },
    installCostPerKwp: { min: 4000, max: 7500, step: 500 },
  },
  locale: "da-DK",
  t: {
    kicker: "№ 01 — Dit solkort",
    headline1: "Hvor meget sol",
    headline2: "modtager dit tag?",
    body: "Indtast en dansk adresse. Vi måler dit tag fra satellit, placerer paneler der, hvor de giver mest udbytte, og viser dig besparelserne over femogtyve år.",
    pressEnter: "Tryk ↵ efter at have valgt en adresse",
    trust1title: "Satellitmåling",
    trust1body: "Tagareal, hældning, orientering og skygge via Google Solar API.",
    trust2title: "Danske tariffer",
    trust2body: "Aktuelle elpriser, nettomåleringsregler og installationsomkostninger for Danmark.",
    trust3title: "Godkendte installatører",
    trust3body: "Tilbud fra Tekniq-godkendte solcelleinstallatører, ikke callcentre.",
    property: "Ejendom",
    scanningRoof: "Indlæser tagdata…",
    noData: "Ingen data tilgængelig.",
    noCoverage: "Denne adresse er endnu ikke dækket af satellitbaserede soldata. Prøv en nærliggende adresse.",
    tryAnother: "Prøv en anden adresse",
    disclaimer: "Estimater er baseret på Google Solar API og typiske danske tariffer. En godkendt installatør giver et bindende tilbud efter et besøg på stedet.",
    systemSize: "Systemstørrelse",
    panel: "panel",
    panels: "paneler",
    max: "maks",
    adjustAssumptions: "Juster forudsætninger",
    electricityPrice: "Elpris",
    feedInPrice: "Nettomåleringspris",
    installCost: "Installationsomkostning",
    selfConsumption: "Egetforbrug",
    calculating: "Beregner…",
    annualProduction: "Årsproduktion",
    kwhPerYear: "kWh/år",
    yearOneSavings: "Besparelser år 1",
    systemCost: "Systemomkostning",
    payback: "Tilbagebetalingstid",
    years: "år",
    over25yr: "> 25 år",
    lifetimeGain: "Netto gevinst 25 år",
    co2Offset: "CO₂-reducering/år",
  },
};

export const eeMarket: MarketConfig = {
  id: "ee",
  countryNameEn: "Estonia",
  countries: ["ee"],
  edition: "Eesti väljaanne",
  cities: "Tallinn · Tartu · Narva · Pärnu",
  placeholder: "Viru väljak 1, Tallinn…",
  solarDeclination: "PÄIKESE DEKLINATSIOON · 59°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.16,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "et-EE",
  t: {
    kicker: "№ 01 — Teie päikesekaart",
    headline1: "Kui palju päikest",
    headline2: "oma katus saab?",
    body: "Sisestage Eesti aadress. Mõõdame teie katuse satelliidilt, paigutame päikesepaneelid sinna, kus need annavad kõige rohkem, ja näitame sääste 25 aasta jooksul.",
    pressEnter: "Vali aadress ja vajuta ↵",
    trust1title: "Satelliitmõõtmine",
    trust1body: "Katusepind, kalle, orientatsioon ja varjutus Google Solar API kaudu.",
    trust2title: "Eesti tariifid",
    trust2body: "Hetke elektrihind, Eleringi võrgulepingutariif ja paigalduskulud Eestis.",
    trust3title: "Sertifitseeritud paigaldajad",
    trust3body: "Pakkumised sertifitseeritud Eesti päikeseenergia paigaldajatelt.",
    property: "Kinnisvara",
    scanningRoof: "Katuse andmete laadimine…",
    noData: "Andmed puuduvad.",
    noCoverage: "See aadress ei ole veel satelliit-päikeseandmetega kaetud. Proovige lähedal asuvat aadressi.",
    tryAnother: "Proovige teist aadressi",
    disclaimer: "Hinnangud põhinevad Google Solar API ja tüüpiliste Eesti tariifide andmetel. Sertifitseeritud paigaldaja esitab pärast kohapealset ülevaatust siduva pakkumise.",
    systemSize: "Süsteemi suurus",
    panel: "paneel",
    panels: "paneeli",
    max: "maks",
    adjustAssumptions: "Muuda eeldusi",
    electricityPrice: "Elektri hind",
    feedInPrice: "Tagasimüügihind",
    installCost: "Paigalduskulud",
    selfConsumption: "Omamahtarvutus",
    calculating: "Arvutamine…",
    annualProduction: "Aastane tootlus",
    kwhPerYear: "kWh/aastas",
    yearOneSavings: "Sääst 1. aastal",
    systemCost: "Süsteemi maksumus",
    payback: "Tasuvusaeg",
    years: "aastat",
    over25yr: "> 25 a.",
    lifetimeGain: "Netokasum 25 aastaga",
    co2Offset: "CO₂ vähendus/aastas",
  },
};

export const esMarket: MarketConfig = {
  id: "es",
  countryNameEn: "Spain",
  countries: ["es"],
  edition: "Edición España",
  cities: "Madrid · Barcelona · Sevilla · Valencia",
  placeholder: "Calle Gran Vía 1, Madrid…",
  solarDeclination: "DECLINACIÓN SOLAR · 40°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.25,
    feedInPrice: 0.06,
    installCostPerKwp: 900,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "es-ES",
  t: {
    kicker: "№ 01 — Un nuevo mapa solar",
    headline1: "Cuánto sol tiene",
    headline2: "tu tejado?",
    body: "Introduce una dirección española. Mediremos tu tejado desde el satélite, colocaremos los paneles donde más rinden y te diremos cuánto ahorrarás en veinticinco años.",
    pressEnter: "Pulsa ↵ tras seleccionar la sugerencia",
    trust1title: "Medición satelital",
    trust1body: "Área, inclinación, orientación y sombras del tejado con Google Solar API.",
    trust2title: "Tarifas españolas",
    trust2body: "Precio de la electricidad, compensación de excedentes PVPC y coste de instalación para España.",
    trust3title: "Instaladores certificados",
    trust3body: "Los presupuestos vienen de instaladores habilitados REE, no de centros de llamadas.",
    property: "Propiedad",
    scanningRoof: "Analizando el tejado…",
    noData: "No hay datos disponibles.",
    noCoverage: "Esta dirección aún no está cubierta por datos solares satelitales. Prueba una dirección cercana o un barrio distinto.",
    tryAnother: "Probar otra dirección",
    disclaimer: "Las estimaciones se basan en el modelado satelital de Google Solar API y tarifas españolas típicas. Un instalador habilitado le proporcionará un presupuesto definitivo tras la visita.",
    systemSize: "Tamaño del sistema",
    panel: "panel",
    panels: "paneles",
    max: "máx",
    adjustAssumptions: "Ajustar supuestos",
    electricityPrice: "Precio electricidad",
    feedInPrice: "Compensación excedentes",
    installCost: "Coste instalación",
    selfConsumption: "Autoconsumo",
    calculating: "Calculando…",
    annualProduction: "Producción anual",
    kwhPerYear: "kWh / año",
    yearOneSavings: "Ahorro año 1",
    systemCost: "Coste del sistema",
    payback: "Amortización",
    years: "años",
    over25yr: "> 25 años",
    lifetimeGain: "Beneficio neto 25 años",
    co2Offset: "Reducción CO₂ / año",
  },
};

export const fiMarket: MarketConfig = {
  id: "fi",
  countryNameEn: "Finland",
  countries: ["fi"],
  edition: "Suomi-painos",
  cities: "Helsinki · Tampere · Turku · Oulu",
  placeholder: "Mannerheimintie 1, Helsinki…",
  solarDeclination: "AURINGON DEKLINAATIO · 62°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.17,
    feedInPrice: 0.04,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "fi-FI",
  t: {
    kicker: "№ 01 — Aurinkosi kartta",
    headline1: "Paljonko kattosi",
    headline2: "tuottaa auringon avulla?",
    body: "Kirjoita suomalainen osoite. Mittaamme kattosi satelliitista, sijoitamme paneelit sinne missä ne tuottavat eniten ja näytämme säästösi 25 vuodessa.",
    pressEnter: "Valitse ehdotus ja paina ↵",
    trust1title: "Satelliittimittaus",
    trust1body: "Katon pinta-ala, kaltevuus, suunta ja varjostus Google Solar API:n kautta.",
    trust2title: "Suomalaiset hinnat",
    trust2body: "Ajankohtaiset sähkön hinnat, syöttötariffi ja asennuskustannukset Suomessa.",
    trust3title: "Sertifioidut asentajat",
    trust3body: "Tarjoukset sertifioiduilta suomalaisilta aurinkopaneeliasentajilta.",
    property: "Kiinteistö",
    scanningRoof: "Ladataan kattodataa…",
    noData: "Tietoja ei saatavilla.",
    noCoverage: "Tämä osoite ei vielä kuulu satelliittipohjaisen aurinkodatan piiriin. Kokeile lähiosoitetta tai muuta kaupunginosaa.",
    tryAnother: "Kokeile toista osoitetta",
    disclaimer: "Arviot perustuvat Google Solar API:n satelliittimallinnukseen ja tyypillisiin suomalaisiin tariffeihin. Sertifioitu asentaja antaa sitovan tarjouksen paikan päällä tehtävän katselmuksen jälkeen.",
    systemSize: "Järjestelmän koko",
    panel: "paneeli",
    panels: "paneelia",
    max: "maks",
    adjustAssumptions: "Muokkaa oletuksia",
    electricityPrice: "Sähkön hinta",
    feedInPrice: "Syöttötariffi",
    installCost: "Asennuskustannukset",
    selfConsumption: "Omakulutus",
    calculating: "Lasketaan…",
    annualProduction: "Vuosituotanto",
    kwhPerYear: "kWh/vuosi",
    yearOneSavings: "Säästöt vuosi 1",
    systemCost: "Järjestelmän hinta",
    payback: "Takaisinmaksuaika",
    years: "vuotta",
    over25yr: "> 25 v.",
    lifetimeGain: "Nettohyöty 25 vuodessa",
    co2Offset: "CO₂-säästö/vuosi",
  },
};

export const frMarket: MarketConfig = {
  id: "fr",
  countryNameEn: "France",
  countries: ["fr"],
  edition: "Édition France",
  cities: "Paris · Lyon · Marseille · Bordeaux",
  placeholder: "1 rue de Rivoli, Paris…",
  solarDeclination: "DÉCLINAISON SOLAIRE · 46°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.25,
    feedInPrice: 0.10,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "fr-FR",
  t: {
    kicker: "№ 01 — La carte du soleil",
    headline1: "Combien de soleil",
    headline2: "sur votre toit?",
    body: "Saisissez une adresse en France. Nous mesurons votre toiture par satellite, positionnons les panneaux là où ils rapportent le plus et vous montrons vos économies sur vingt-cinq ans.",
    pressEnter: "Appuyez sur ↵ après avoir sélectionné",
    trust1title: "Mesure satellitaire",
    trust1body: "Surface, inclinaison, orientation et ombrage du toit par Google Solar API.",
    trust2title: "Tarif EDF / OA",
    trust2body: "Prix de l'électricité EDF, tarif de rachat obligation d'achat et coûts d'installation pour la France.",
    trust3title: "Installateurs RGE",
    trust3body: "Les devis viennent d'installateurs RGE certifiés, pas de centres d'appel.",
    property: "Propriété",
    scanningRoof: "Analyse du toit en cours…",
    noData: "Aucune donnée disponible.",
    noCoverage: "Cette adresse n'est pas encore couverte par les données satellitaires. Essayez une adresse voisine ou un autre quartier.",
    tryAnother: "Essayer une autre adresse",
    disclaimer: "Les estimations sont basées sur la modélisation satellitaire Google Solar API et les tarifs français typiques. Un installateur RGE vous fournira un devis définitif après visite sur site.",
    systemSize: "Taille du système",
    panel: "panneau",
    panels: "panneaux",
    max: "max",
    adjustAssumptions: "Ajuster les hypothèses",
    electricityPrice: "Prix de l'électricité",
    feedInPrice: "Tarif de rachat",
    installCost: "Coût d'installation",
    selfConsumption: "Autoconsommation",
    calculating: "Calcul en cours…",
    annualProduction: "Production annuelle",
    kwhPerYear: "kWh / an",
    yearOneSavings: "Économies année 1",
    systemCost: "Coût du système",
    payback: "Amortissement",
    years: "ans",
    over25yr: "> 25 ans",
    lifetimeGain: "Gain net sur 25 ans",
    co2Offset: "Réduction CO₂ / an",
  },
};

export const gbMarket: MarketConfig = {
  id: "gb",
  countryNameEn: "United Kingdom",
  countries: ["gb"],
  edition: "UK edition",
  cities: "London · Manchester · Edinburgh · Bristol",
  placeholder: "1 Baker Street, London…",
  solarDeclination: "SOLAR DECLINATION · 52°N",
  currencySymbol: "£",
  defaults: {
    electricityPrice: 0.26,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.10, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "en-GB",
  t: {
    kicker: "№ 01 — A new map of the sun",
    headline1: "See the amount of the sun",
    headline2: "on your roof.",
    body: "Type a UK address. We'll measure your roof from satellite, place panels where they earn the most, and tell you what they'll save you in twenty-five years.",
    pressEnter: "Press ↵ after selecting from the suggestions",
    trust1title: "Satellite-measured",
    trust1body: "Roof area, pitch, azimuth and shading from Google Solar API.",
    trust2title: "SEG & MCS rates",
    trust2body: "Current Ofgem tariffs, Smart Export Guarantee rates, and MCS-benchmarked install costs for the UK.",
    trust3title: "MCS-certified installers",
    trust3body: "Quotes come from MCS-certified UK installers, not call centres.",
    property: "Property",
    scanningRoof: "Scanning roof data…",
    noData: "No data available.",
    noCoverage: "This address isn't covered by satellite solar data yet. Try a nearby town or a different street.",
    tryAnother: "Try another address",
    disclaimer: "Estimates are based on Google Solar API satellite modelling and typical UK tariffs. An MCS-certified installer will provide a binding quote after a site survey.",
    systemSize: "System size",
    panel: "panel",
    panels: "panels",
    max: "max",
    adjustAssumptions: "Adjust assumptions",
    electricityPrice: "Electricity price",
    feedInPrice: "SEG export rate",
    installCost: "Install cost",
    selfConsumption: "Self-consumption",
    calculating: "Calculating…",
    annualProduction: "Annual production",
    kwhPerYear: "kWh / yr",
    yearOneSavings: "Year-one savings",
    systemCost: "System cost",
    payback: "Payback",
    years: "years",
    over25yr: "> 25 yr",
    lifetimeGain: "25-year net gain",
    co2Offset: "CO₂ offset / yr",
  },
};

export const grMarket: MarketConfig = {
  id: "gr",
  countryNameEn: "Greece",
  countries: ["gr"],
  edition: "Ελληνική έκδοση",
  cities: "Αθήνα · Θεσσαλονίκη · Πάτρα · Ηράκλειο",
  placeholder: "Πανεπιστημίου 1, Αθήνα…",
  solarDeclination: "ΗΛΙΑΚΗ ΑΠΟΚΛΙΣΗ · 38°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.18,
    feedInPrice: 0.07,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.55,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "el-GR",
  t: {
    kicker: "№ 01 — Ο ηλιακός χάρτης σας",
    headline1: "Πόσο ήλιο δέχεται",
    headline2: "η στέγη σας;",
    body: "Πληκτρολογήστε ελληνική διεύθυνση. Θα μετρήσουμε τη στέγη σας από δορυφόρο, θα τοποθετήσουμε πάνελ εκεί που αποδίδουν περισσότερο και θα σας δείξουμε τις εξοικονομήσεις σε 25 χρόνια.",
    pressEnter: "Πατήστε ↵ αφού επιλέξετε πρόταση",
    trust1title: "Δορυφορική μέτρηση",
    trust1body: "Εμβαδόν, κλίση, προσανατολισμός και σκίαση στέγης μέσω Google Solar API.",
    trust2title: "Ελληνικά τιμολόγια",
    trust2body: "Τρέχουσες τιμές ηλεκτρισμού, εικονικό net metering ΔΕΔΔΗΕ και κόστος εγκατάστασης.",
    trust3title: "Πιστοποιημένοι εγκαταστάτες",
    trust3body: "Προσφορές από αδειοδοτημένους εγκαταστάτες φωτοβολταϊκών στην Ελλάδα.",
    property: "Ακίνητο",
    scanningRoof: "Φόρτωση δεδομένων στέγης…",
    noData: "Δεν υπάρχουν διαθέσιμα δεδομένα.",
    noCoverage: "Αυτή η διεύθυνση δεν καλύπτεται ακόμα από δορυφορικά ηλιακά δεδομένα. Δοκιμάστε μια κοντινή διεύθυνση.",
    tryAnother: "Δοκιμάστε άλλη διεύθυνση",
    disclaimer: "Οι εκτιμήσεις βασίζονται στο Google Solar API και σε τυπικά ελληνικά τιμολόγια. Αδειοδοτημένος εγκαταστάτης θα παρέχει δεσμευτική προσφορά μετά από επιτόπια επίσκεψη.",
    systemSize: "Μέγεθος συστήματος",
    panel: "πάνελ",
    panels: "πάνελ",
    max: "μέγ",
    adjustAssumptions: "Προσαρμογή παραδοχών",
    electricityPrice: "Τιμή ηλεκτρισμού",
    feedInPrice: "Τιμή net metering",
    installCost: "Κόστος εγκατάστασης",
    selfConsumption: "Αυτοκατανάλωση",
    calculating: "Υπολογισμός…",
    annualProduction: "Ετήσια παραγωγή",
    kwhPerYear: "kWh/έτος",
    yearOneSavings: "Εξοικονόμηση έτους 1",
    systemCost: "Κόστος συστήματος",
    payback: "Απόσβεση",
    years: "χρόνια",
    over25yr: "> 25 χρ.",
    lifetimeGain: "Καθαρό κέρδος 25 ετών",
    co2Offset: "Μείωση CO₂/έτος",
  },
};

export const hrMarket: MarketConfig = {
  id: "hr",
  countryNameEn: "Croatia",
  countries: ["hr"],
  edition: "Hrvatsko izdanje",
  cities: "Zagreb · Split · Rijeka · Osijek",
  placeholder: "Ilica 1, Zagreb…",
  solarDeclination: "SUNČEVA DEKLINACIJA · 45°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.13,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "hr-HR",
  t: {
    kicker: "№ 01 — Vaša sunčana karta",
    headline1: "Koliko sunca ima",
    headline2: "na vašem krovu?",
    body: "Unesite hrvatsku adresu. Izmjerit ćemo vaš krov satelitom, postaviti panele tamo gdje daju najviše i pokazati vam uštedine kroz dvadeset i pet godina.",
    pressEnter: "Odaberite adresu i pritisnite ↵",
    trust1title: "Satelitsko mjerenje",
    trust1body: "Površina, nagib, orijentacija i zasjenjenje krova putem Google Solar API.",
    trust2title: "Hrvatski tarifni sustav",
    trust2body: "Aktualne cijene struje, neto mjerenje HEP-a i troškovi instalacije u Hrvatskoj.",
    trust3title: "Certificirani instalateri",
    trust3body: "Ponude od licenciranih instalatera fotonaponskih sustava u Hrvatskoj.",
    property: "Nekretnina",
    scanningRoof: "Učitavanje podataka o krovu…",
    noData: "Nema dostupnih podataka.",
    noCoverage: "Ova adresa još nije pokrivena satelitskim solarnim podacima. Pokušajte s obližnjom adresom.",
    tryAnother: "Pokušajte s drugom adresom",
    disclaimer: "Procjene se temelje na Google Solar API satelitskom modeliranju i tipičnim hrvatskim tarifama. Licencirani instalater dat će obvezujuću ponudu nakon pregleda lokacije.",
    systemSize: "Veličina sustava",
    panel: "panel",
    panels: "panela",
    max: "maks",
    adjustAssumptions: "Prilagodi pretpostavke",
    electricityPrice: "Cijena struje",
    feedInPrice: "Cijena neto mjerenja",
    installCost: "Troškovi instalacije",
    selfConsumption: "Vlastita potrošnja",
    calculating: "Izračunavanje…",
    annualProduction: "Godišnja proizvodnja",
    kwhPerYear: "kWh/god.",
    yearOneSavings: "Uštedine 1. godina",
    systemCost: "Cijena sustava",
    payback: "Povrat investicije",
    years: "godina",
    over25yr: "> 25 god.",
    lifetimeGain: "Neto zarada 25 god.",
    co2Offset: "Smanjenje CO₂/god.",
  },
};

export const huMarket: MarketConfig = {
  id: "hu",
  countryNameEn: "Hungary",
  countries: ["hu"],
  edition: "Magyar kiadás",
  cities: "Budapest · Debrecen · Miskolc · Pécs",
  placeholder: "Andrássy út 1, Budapest…",
  solarDeclination: "NAPELTÉRÉS · 47°N",
  currencySymbol: "Ft",
  defaults: {
    electricityPrice: 100,
    feedInPrice: 25,
    installCostPerKwp: 350000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 20, max: 300, step: 5 },
    feedInPrice: { min: 0, max: 100, step: 5 },
    installCostPerKwp: { min: 100000, max: 400000, step: 10000 },
  },
  locale: "hu-HU",
  t: {
    kicker: "№ 01 — Napenergia-térképe",
    headline1: "Mennyi nap éri",
    headline2: "az Ön tetőjét?",
    body: "Adjon meg egy magyarországi címet. Műholdról megmérjük a tetőjét, a paneleket oda helyezzük, ahol a legtöbbet hozzák, és megmutatjuk, mennyit spórolhat huszonöt év alatt.",
    pressEnter: "Válasszon ajánlatot, majd nyomja meg a ↵ billentyűt",
    trust1title: "Műholdas mérés",
    trust1body: "Tetőfelület, dőlésszög, tájolás és árnyékolás Google Solar API segítségével.",
    trust2title: "Magyar METÁR-rendszer",
    trust2body: "Aktuális villamosenergia-árak, METÁR KÁT betáplálási díj és magyarországi telepítési költségek.",
    trust3title: "Tanúsított telepítők",
    trust3body: "Ajánlatok hazai, engedéllyel rendelkező napelem-telepítőktől.",
    property: "Ingatlan",
    scanningRoof: "Tetőadatok betöltése…",
    noData: "Nem állnak rendelkezésre adatok.",
    noCoverage: "Ezt a címet még nem fedi le a műholdas napenergiai adatbázis. Próbáljon egy közeli címet.",
    tryAnother: "Próbáljon meg egy másik címet",
    disclaimer: "A becslések a Google Solar API műholdas modellezésén és a tipikus magyarországi tarifákon alapulnak. A tanúsított telepítő helyszíni felmérés után kötelező érvényű ajánlatot ad.",
    systemSize: "Rendszer mérete",
    panel: "panel",
    panels: "panel",
    max: "max",
    adjustAssumptions: "Feltételezések módosítása",
    electricityPrice: "Villamosenergia-ár",
    feedInPrice: "Betáplálási díj",
    installCost: "Telepítési költség",
    selfConsumption: "Saját fogyasztás",
    calculating: "Számítás…",
    annualProduction: "Éves termelés",
    kwhPerYear: "kWh/év",
    yearOneSavings: "Megtakarítás 1. év",
    systemCost: "Rendszerköltség",
    payback: "Megtérülés",
    years: "év",
    over25yr: "> 25 év",
    lifetimeGain: "Nettó nyereség 25 év",
    co2Offset: "CO₂-megtakarítás/év",
  },
};

export const ieMarket: MarketConfig = {
  id: "ie",
  countryNameEn: "Ireland",
  countries: ["ie"],
  edition: "Ireland edition",
  cities: "Dublin · Cork · Limerick · Galway",
  placeholder: "1 O'Connell Street, Dublin…",
  solarDeclination: "SOLAR DECLINATION · 53°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.36,
    feedInPrice: 0.09,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "en-IE",
  t: {
    kicker: "№ 01 — A new map of the sun",
    headline1: "See the amount of the sun",
    headline2: "on your roof.",
    body: "Type an Irish address. We'll measure your roof from satellite, place panels where they earn the most, and tell you what they'll save you in twenty-five years.",
    pressEnter: "Press ↵ after selecting from the suggestions",
    trust1title: "Satellite-measured",
    trust1body: "Roof area, pitch, azimuth and shading from Google Solar API.",
    trust2title: "SEAI Clean Export rates",
    trust2body: "Current electricity tariffs, SEAI Clean Export Guarantee rates, and typical Irish install costs.",
    trust3title: "SEAI-registered installers",
    trust3body: "Quotes come from SEAI-registered solar installers, not call centres.",
    property: "Property",
    scanningRoof: "Scanning roof data…",
    noData: "No data available.",
    noCoverage: "This address isn't covered by satellite solar data yet. Try a nearby town or a different street.",
    tryAnother: "Try another address",
    disclaimer: "Estimates are based on Google Solar API satellite modelling and typical Irish tariffs. A SEAI-registered installer will provide a binding quote after a site survey.",
    systemSize: "System size",
    panel: "panel",
    panels: "panels",
    max: "max",
    adjustAssumptions: "Adjust assumptions",
    electricityPrice: "Electricity price",
    feedInPrice: "Clean Export rate",
    installCost: "Install cost",
    selfConsumption: "Self-consumption",
    calculating: "Calculating…",
    annualProduction: "Annual production",
    kwhPerYear: "kWh / yr",
    yearOneSavings: "Year-one savings",
    systemCost: "System cost",
    payback: "Payback",
    years: "years",
    over25yr: "> 25 yr",
    lifetimeGain: "25-year net gain",
    co2Offset: "CO₂ offset / yr",
  },
};

export const isMarket: MarketConfig = {
  id: "is",
  countryNameEn: "Iceland",
  countries: ["is"],
  edition: "Íslensk útgáfa",
  cities: "Reykjavík · Akureyri · Kópavogur · Hafnarfjörður",
  placeholder: "Laugavegur 1, Reykjavík…",
  solarDeclination: "SÓLHALLI · 65°N",
  currencySymbol: "kr",
  defaults: {
    electricityPrice: 22,
    feedInPrice: 5,
    installCostPerKwp: 150000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 5, max: 80, step: 1 },
    feedInPrice: { min: 0, max: 20, step: 1 },
    installCostPerKwp: { min: 80000, max: 150000, step: 10000 },
  },
  locale: "is-IS",
  t: {
    kicker: "№ 01 — Sólkort þitt",
    headline1: "Hversu mikla sól",
    headline2: "fær þakið þitt?",
    body: "Sláðu inn íslenskt heimilisfang. Við mælum þakið þitt með gervihnetti, setjum sólarplötur þar sem þær skila mestu og sýnum þér sparnaðinn yfir 25 ár.",
    pressEnter: "Veldu tillögu og ýttu á ↵",
    trust1title: "Gervihnetjamæling",
    trust1body: "Þakflatarmál, halli, stefna og skuggi með Google Solar API.",
    trust2title: "Íslenskt gjaldskrárkerfi",
    trust2body: "Rafmagnsverð Landsnets og Orkuveitu Reykjavíkur ásamt uppkaupstaxta og uppsetningarkostnaði.",
    trust3title: "Viðurkendir verktakar",
    trust3body: "Tilboð frá viðurkenndum sólorku-verktökum á Íslandi.",
    property: "Fasteign",
    scanningRoof: "Hleður þakgögn…",
    noData: "Engar upplýsingar tiltækar.",
    noCoverage: "Þetta heimilisfang er ekki enn hluti af gervihnetja-sólgagnagrunni. Prófaðu nálægt heimilisfang.",
    tryAnother: "Prófaðu annað heimilisfang",
    disclaimer: "Áætlanir eru byggðar á gervihnettjalíkani Google Solar API og dæmigerðum íslenskum gjaldskrám. Viðurkenndur verktaki gefur bindandi tilboð eftir vettvangsskoðun.",
    systemSize: "Stærð kerfis",
    panel: "plata",
    panels: "plötur",
    max: "hámark",
    adjustAssumptions: "Breyta forsendum",
    electricityPrice: "Rafmagnsverð",
    feedInPrice: "Uppkaupstaxti",
    installCost: "Uppsetningarkostnaður",
    selfConsumption: "Eigin notkun",
    calculating: "Reiknar…",
    annualProduction: "Árleg framleiðsla",
    kwhPerYear: "kWh/ár",
    yearOneSavings: "Sparnaður 1. ár",
    systemCost: "Kerfiskostnaður",
    payback: "Endurgreiðslutími",
    years: "ár",
    over25yr: "> 25 ár",
    lifetimeGain: "Nettó hagnaður 25 ár",
    co2Offset: "CO₂-minnkun/ár",
  },
};

export const itMarket: MarketConfig = {
  id: "it",
  countryNameEn: "Italy",
  countries: ["it"],
  edition: "Edizione Italia",
  cities: "Roma · Milano · Napoli · Torino",
  placeholder: "Via del Corso 1, Roma…",
  solarDeclination: "DECLINAZIONE SOLARE · 42°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.33,
    feedInPrice: 0.08,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "it-IT",
  t: {
    kicker: "№ 01 — La mappa del sole",
    headline1: "Quanto sole ha",
    headline2: "il tuo tetto?",
    body: "Inserisci un indirizzo italiano. Misuriamo il tuo tetto dal satellite, posizioniamo i pannelli dove rendono di più e ti mostriamo quanto risparmierai in venticinque anni.",
    pressEnter: "Premi ↵ dopo aver selezionato il suggerimento",
    trust1title: "Misurazione satellitare",
    trust1body: "Area, inclinazione, orientamento e ombreggiatura del tetto tramite Google Solar API.",
    trust2title: "Scambio sul posto GSE",
    trust2body: "Prezzi dell'energia, tariffa di scambio sul posto GSE e costi di installazione per l'Italia.",
    trust3title: "Installatori certificati",
    trust3body: "I preventivi provengono da installatori certificati SEA/GSE, non da call centre.",
    property: "Proprietà",
    scanningRoof: "Analisi del tetto in corso…",
    noData: "Nessun dato disponibile.",
    noCoverage: "Questo indirizzo non è ancora coperto dai dati solari satellitari. Prova un indirizzo vicino o un quartiere diverso.",
    tryAnother: "Prova un altro indirizzo",
    disclaimer: "Le stime si basano sulla modellazione satellitare Google Solar API e sulle tariffe italiane tipiche. Un installatore certificato GSE fornirà un preventivo definitivo dopo il sopralluogo.",
    systemSize: "Dimensione del sistema",
    panel: "pannello",
    panels: "pannelli",
    max: "max",
    adjustAssumptions: "Modifica i parametri",
    electricityPrice: "Prezzo dell'energia",
    feedInPrice: "Scambio sul posto",
    installCost: "Costo di installazione",
    selfConsumption: "Autoconsumo",
    calculating: "Calcolo in corso…",
    annualProduction: "Produzione annuale",
    kwhPerYear: "kWh / anno",
    yearOneSavings: "Risparmio anno 1",
    systemCost: "Costo del sistema",
    payback: "Ammortamento",
    years: "anni",
    over25yr: "> 25 anni",
    lifetimeGain: "Guadagno netto 25 anni",
    co2Offset: "Riduzione CO₂ / anno",
  },
};

export const ltMarket: MarketConfig = {
  id: "lt",
  countryNameEn: "Lithuania",
  countries: ["lt"],
  edition: "Lietuvos leidimas",
  cities: "Vilnius · Kaunas · Klaipėda · Šiauliai",
  placeholder: "Gedimino pr. 1, Vilnius…",
  solarDeclination: "SAULĖS DEKLINACIJA · 56°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.17,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "lt-LT",
  t: {
    kicker: "№ 01 — Saulės žemėlapis",
    headline1: "Kiek saulės gauna",
    headline2: "tavo stogas?",
    body: "Įveskite Lietuvos adresą. Išmatuosime jūsų stogą iš palydovo, išdėliosime panelius ten, kur jie duoda daugiausiai naudos, ir parodysime sutaupymus per 25 metus.",
    pressEnter: "Pasirinkite adresą ir spauskite ↵",
    trust1title: "Palydovinis matavimas",
    trust1body: "Stogo plotas, nuolydis, orientacija ir šešėliavimas naudojant Google Solar API.",
    trust2title: "Lietuviški tarifai",
    trust2body: "Dabartinės elektros kainos, LITGRID atsiskaitomoji kaina ir įrengimo kaštai Lietuvoje.",
    trust3title: "Sertifikuoti montuotojai",
    trust3body: "Pasiūlymai iš licencijuotų Lietuvos saulės energetikos montuotojų.",
    property: "Nekilnojamasis turtas",
    scanningRoof: "Kraunami stogo duomenys…",
    noData: "Duomenų nėra.",
    noCoverage: "Šis adresas dar nėra padengtas palydoviniais saulės duomenimis. Pabandykite artimą adresą.",
    tryAnother: "Pabandykite kitą adresą",
    disclaimer: "Įvertinimai grindžiami Google Solar API palydoviniu modeliavimu ir tipiniais Lietuvos tarifais. Licencijuotas montuotojas pateiks privalomos galios pasiūlymą po vietos apžiūros.",
    systemSize: "Sistemos dydis",
    panel: "plokštė",
    panels: "plokščių",
    max: "maks",
    adjustAssumptions: "Koreguoti prielaidas",
    electricityPrice: "Elektros kaina",
    feedInPrice: "Perpardavimo kaina",
    installCost: "Įrengimo kaštai",
    selfConsumption: "Savivartojimas",
    calculating: "Skaičiuojama…",
    annualProduction: "Metinė gamyba",
    kwhPerYear: "kWh/metai",
    yearOneSavings: "Sutaupymai 1 metai",
    systemCost: "Sistemos kaina",
    payback: "Atsipirkimas",
    years: "metai",
    over25yr: "> 25 m.",
    lifetimeGain: "Grynasis pelnas 25 m.",
    co2Offset: "CO₂ sumažinimas/m.",
  },
};

export const luMarket: MarketConfig = {
  id: "lu",
  countryNameEn: "Luxembourg",
  countries: ["lu"],
  edition: "Édition Luxembourg",
  cities: "Luxembourg · Esch-sur-Alzette · Differdange",
  placeholder: "Avenue de la Liberté 1, Luxembourg…",
  solarDeclination: "DÉCLINAISON SOLAIRE · 50°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.16,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "fr-LU",
  t: {
    kicker: "№ 01 — Votre carte solaire",
    headline1: "Combien de soleil",
    headline2: "sur votre toit?",
    body: "Saisissez une adresse luxembourgeoise. Nous mesurons votre toiture par satellite, positionnons les panneaux là où ils rapportent le plus et vous montrons vos économies sur vingt-cinq ans.",
    pressEnter: "Appuyez sur ↵ après avoir sélectionné",
    trust1title: "Mesure satellitaire",
    trust1body: "Surface, inclinaison, orientation et ombrage du toit par Google Solar API.",
    trust2title: "Tarifs Creos / ILR",
    trust2body: "Prix de l'électricité, tarif d'injection ILR et coûts d'installation au Luxembourg.",
    trust3title: "Installateurs agréés",
    trust3body: "Les devis viennent d'installateurs agréés au Luxembourg, pas de centres d'appel.",
    property: "Propriété",
    scanningRoof: "Analyse du toit en cours…",
    noData: "Aucune donnée disponible.",
    noCoverage: "Cette adresse n'est pas encore couverte par les données satellitaires. Essayez une adresse voisine.",
    tryAnother: "Essayer une autre adresse",
    disclaimer: "Les estimations sont basées sur la modélisation satellitaire Google Solar API et les tarifs luxembourgeois typiques. Un installateur agréé vous fournira un devis définitif après visite sur site.",
    systemSize: "Taille du système",
    panel: "panneau",
    panels: "panneaux",
    max: "max",
    adjustAssumptions: "Ajuster les hypothèses",
    electricityPrice: "Prix de l'électricité",
    feedInPrice: "Tarif d'injection",
    installCost: "Coût d'installation",
    selfConsumption: "Autoconsommation",
    calculating: "Calcul en cours…",
    annualProduction: "Production annuelle",
    kwhPerYear: "kWh / an",
    yearOneSavings: "Économies année 1",
    systemCost: "Coût du système",
    payback: "Amortissement",
    years: "ans",
    over25yr: "> 25 ans",
    lifetimeGain: "Gain net sur 25 ans",
    co2Offset: "Réduction CO₂ / an",
  },
};

export const lvMarket: MarketConfig = {
  id: "lv",
  countryNameEn: "Latvia",
  countries: ["lv"],
  edition: "Latvijas izdevums",
  cities: "Rīga · Daugavpils · Liepāja · Jelgava",
  placeholder: "Brīvības iela 1, Rīga…",
  solarDeclination: "SAULES DEKLINĀCIJA · 57°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.19,
    feedInPrice: 0.05,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "lv-LV",
  t: {
    kicker: "№ 01 — Jūsu saules karte",
    headline1: "Cik daudz saules",
    headline2: "uz jūsu jumta?",
    body: "Ievadiet Latvijas adresi. Mēs izmērīsim jūsu jumtu no satelīta, izvietosim paneļus tur, kur tie dod vairāk, un parādīsim ietaupījumus 25 gadu laikā.",
    pressEnter: "Izvēlieties adresi un nospiediet ↵",
    trust1title: "Satelīta mērījumi",
    trust1body: "Jumta laukums, slīpums, orientācija un ēnojums, izmantojot Google Solar API.",
    trust2title: "Latvijas tarifi",
    trust2body: "Pašreizējās elektroenerģijas cenas, Sadales tīkla obligātā iepirkuma cena un uzstādīšanas izmaksas Latvijā.",
    trust3title: "Sertificēti uzstādītāji",
    trust3body: "Piedāvājumi no licencētiem saules enerģijas uzstādītājiem Latvijā.",
    property: "Nekustamais īpašums",
    scanningRoof: "Tiek ielādēti jumta dati…",
    noData: "Dati nav pieejami.",
    noCoverage: "Šī adrese vēl nav iekļauta satelīta saules datu pārklājumā. Mēģiniet tuvumā esošu adresi.",
    tryAnother: "Mēģiniet citu adresi",
    disclaimer: "Aplēses balstītas uz Google Solar API satelīta modelēšanu un tipiskajiem Latvijas tarifiem. Licencēts uzstādītājs pēc vietas apsekošanas sniegs saistošu piedāvājumu.",
    systemSize: "Sistēmas izmērs",
    panel: "panelis",
    panels: "paneļu",
    max: "maks",
    adjustAssumptions: "Mainīt pieņēmumus",
    electricityPrice: "Elektroenerģijas cena",
    feedInPrice: "Iepirkuma cena",
    installCost: "Uzstādīšanas izmaksas",
    selfConsumption: "Pašpatēriņš",
    calculating: "Aprēķina…",
    annualProduction: "Gada ražošana",
    kwhPerYear: "kWh/gadā",
    yearOneSavings: "Ietaupījums 1. gadā",
    systemCost: "Sistēmas izmaksas",
    payback: "Atmaksāšanās laiks",
    years: "gadi",
    over25yr: "> 25 g.",
    lifetimeGain: "Neto peļņa 25 g.",
    co2Offset: "CO₂ samazinājums/g.",
  },
};

export const mtMarket: MarketConfig = {
  id: "mt",
  countryNameEn: "Malta",
  countries: ["mt"],
  edition: "Malta edition",
  cities: "Valletta · Mdina · Sliema · Marsaxlokk",
  placeholder: "Triq ir-Repubblika 1, Valletta…",
  solarDeclination: "SOLAR DECLINATION · 36°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.13,
    feedInPrice: 0.06,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.65,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "en-MT",
  t: {
    kicker: "№ 01 — Your solar map",
    headline1: "See the amount of the sun",
    headline2: "on your roof.",
    body: "Enter a Maltese address. We'll measure your roof from satellite, place panels where they earn the most, and show you your savings over twenty-five years.",
    pressEnter: "Press ↵ after selecting from the suggestions",
    trust1title: "Satellite-measured",
    trust1body: "Roof area, pitch, azimuth and shading from Google Solar API.",
    trust2title: "ARMS feed-in tariff",
    trust2body: "Current Enemalta electricity rates, ARMS solar feed-in tariff, and local install costs for Malta.",
    trust3title: "MCCAA-registered installers",
    trust3body: "Quotes come from MCCAA-registered solar installers, not call centres.",
    property: "Property",
    scanningRoof: "Scanning roof data…",
    noData: "No data available.",
    noCoverage: "This address isn't covered by satellite solar data yet. Try a nearby address.",
    tryAnother: "Try another address",
    disclaimer: "Estimates are based on Google Solar API satellite modelling and typical Maltese tariffs. A MCCAA-registered installer will provide a binding quote after a site survey.",
    systemSize: "System size",
    panel: "panel",
    panels: "panels",
    max: "max",
    adjustAssumptions: "Adjust assumptions",
    electricityPrice: "Electricity price",
    feedInPrice: "Feed-in tariff",
    installCost: "Install cost",
    selfConsumption: "Self-consumption",
    calculating: "Calculating…",
    annualProduction: "Annual production",
    kwhPerYear: "kWh / yr",
    yearOneSavings: "Year-one savings",
    systemCost: "System cost",
    payback: "Payback",
    years: "years",
    over25yr: "> 25 yr",
    lifetimeGain: "25-year net gain",
    co2Offset: "CO₂ offset / yr",
  },
};

export const nlMarket: MarketConfig = {
  id: "nl",
  countryNameEn: "Netherlands",
  countries: ["nl"],
  edition: "Nederlandse editie",
  cities: "Amsterdam · Rotterdam · Den Haag · Utrecht",
  placeholder: "Damrak 1, Amsterdam…",
  solarDeclination: "ZONSDECLINATIE · 52°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.29,
    feedInPrice: 0.07,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "nl-NL",
  t: {
    kicker: "№ 01 — Uw nieuwe zonnekaart",
    headline1: "Hoeveel zon",
    headline2: "krijgt uw dak?",
    body: "Voer een Nederlands adres in. We meten uw dak via satelliet, plaatsen panelen waar ze het meest opleveren en laten u zien hoeveel u in vijfentwintig jaar bespaart.",
    pressEnter: "Druk op ↵ na het selecteren van een suggestie",
    trust1title: "Satellietmeting",
    trust1body: "Dakoppervlak, helling, oriëntatie en schaduw via Google Solar API.",
    trust2title: "Salderingsregeling",
    trust2body: "Actuele energieprijzen, salderingsregeling Netbeheer Nederland en installatiekosten.",
    trust3title: "Gecertificeerde installateurs",
    trust3body: "Offertes van ESCOS-erkende installateurs, geen callcenters.",
    property: "Woning",
    scanningRoof: "Dakgegevens laden…",
    noData: "Geen gegevens beschikbaar.",
    noCoverage: "Dit adres valt nog niet onder satelliet-zonnedata. Probeer een naburig adres of een andere wijk.",
    tryAnother: "Ander adres proberen",
    disclaimer: "Schattingen zijn gebaseerd op Google Solar API en typische Nederlandse tarieven. Een erkende installateur geeft na een plaatsbezoek een bindende offerte.",
    systemSize: "Systeemgrootte",
    panel: "paneel",
    panels: "panelen",
    max: "max",
    adjustAssumptions: "Aannames aanpassen",
    electricityPrice: "Elektriciteitsprijs",
    feedInPrice: "Salderingstarief",
    installCost: "Installatiekosten",
    selfConsumption: "Eigenverbruik",
    calculating: "Berekenen…",
    annualProduction: "Jaarproductie",
    kwhPerYear: "kWh/jaar",
    yearOneSavings: "Besparing jaar 1",
    systemCost: "Systeemkosten",
    payback: "Terugverdientijd",
    years: "jaar",
    over25yr: "> 25 jr",
    lifetimeGain: "Netto winst 25 jaar",
    co2Offset: "CO₂-reductie/jaar",
  },
};

export const noMarket: MarketConfig = {
  id: "no",
  countryNameEn: "Norway",
  countries: ["no"],
  edition: "Norsk utgave",
  cities: "Oslo · Bergen · Trondheim · Stavanger",
  placeholder: "Karl Johans gate 1, Oslo…",
  solarDeclination: "SOLFALLSDEKLINASJON · 60°N",
  currencySymbol: "kr",
  defaults: {
    electricityPrice: 1.50,
    feedInPrice: 0.30,
    installCostPerKwp: 12000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.20, max: 5.00, step: 0.10 },
    feedInPrice: { min: 0, max: 2.00, step: 0.05 },
    installCostPerKwp: { min: 5000, max: 12000, step: 500 },
  },
  locale: "nb-NO",
  t: {
    kicker: "№ 01 — Ditt solkart",
    headline1: "Hvor mye sol",
    headline2: "får taket ditt?",
    body: "Skriv inn en norsk adresse. Vi måler taket ditt fra satellitt, plasserer paneler der de gir mest utbytte og viser deg besparelsene over femogtyve år.",
    pressEnter: "Velg en adresse og trykk ↵",
    trust1title: "Satellittmåling",
    trust1body: "Takareal, helning, orientering og skygge via Google Solar API.",
    trust2title: "NVE-tariffer",
    trust2body: "Aktuelle strømpriser, plusskundeordning fra NVE og installasjonskostnader i Norge.",
    trust3title: "Godkjente installatører",
    trust3body: "Tilbud fra Nelfo-godkjente solcelleinstallatører, ikke callsentre.",
    property: "Eiendom",
    scanningRoof: "Laster takdata…",
    noData: "Ingen data tilgjengelig.",
    noCoverage: "Denne adressen dekkes ikke av satellittbaserte soldata ennå. Prøv en nærliggende adresse.",
    tryAnother: "Prøv en annen adresse",
    disclaimer: "Estimater er basert på Google Solar API og typiske norske tariffer. En godkjent installatør gir et bindende tilbud etter befaring.",
    systemSize: "Systemstørrelse",
    panel: "panel",
    panels: "paneler",
    max: "maks",
    adjustAssumptions: "Juster forutsetninger",
    electricityPrice: "Strømpris",
    feedInPrice: "Plusskundepris",
    installCost: "Installasjonskostnad",
    selfConsumption: "Egetforbruk",
    calculating: "Beregner…",
    annualProduction: "Årsproduksjon",
    kwhPerYear: "kWh/år",
    yearOneSavings: "Besparelser år 1",
    systemCost: "Systemkostnad",
    payback: "Tilbakebetalingstid",
    years: "år",
    over25yr: "> 25 år",
    lifetimeGain: "Netto gevinst 25 år",
    co2Offset: "CO₂-reduksjon/år",
  },
};

export const plMarket: MarketConfig = {
  id: "pl",
  countryNameEn: "Poland",
  countries: ["pl"],
  edition: "Wydanie Polska",
  cities: "Warszawa · Kraków · Wrocław · Poznań",
  placeholder: "ul. Nowy Świat 1, Warszawa…",
  solarDeclination: "DEKLINACJA SŁONECZNA · 52°N",
  currencySymbol: "zł",
  defaults: {
    electricityPrice: 0.95,
    feedInPrice: 0.20,
    installCostPerKwp: 4000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.20, max: 2.00, step: 0.05 },
    feedInPrice: { min: 0, max: 1.00, step: 0.02 },
    installCostPerKwp: { min: 2000, max: 4000, step: 200 },
  },
  locale: "pl-PL",
  t: {
    kicker: "№ 01 — Twoja mapa słoneczna",
    headline1: "Ile słońca pada",
    headline2: "na Twój dach?",
    body: "Wpisz polski adres. Zmierzymy twój dach z satelity, ustawimy panele tam, gdzie zarabiają najwięcej, i pokażemy, ile zaoszczędzisz przez dwadzieścia pięć lat.",
    pressEnter: "Wybierz adres i naciśnij ↵",
    trust1title: "Pomiar satelitarny",
    trust1body: "Powierzchnia dachu, nachylenie, orientacja i zacienienie przez Google Solar API.",
    trust2title: "System net-billing URE",
    trust2body: "Aktualne ceny prądu, rozliczenie net-billing URE oraz koszty instalacji w Polsce.",
    trust3title: "Certyfikowani instalatorzy",
    trust3body: "Oferty od certyfikowanych instalatorów fotowoltaiki w Polsce, nie call center.",
    property: "Nieruchomość",
    scanningRoof: "Ładowanie danych dachu…",
    noData: "Brak dostępnych danych.",
    noCoverage: "Ten adres nie jest jeszcze objęty satelitarnymi danymi słonecznymi. Spróbuj pobliskiego adresu.",
    tryAnother: "Spróbuj innego adresu",
    disclaimer: "Szacunki opierają się na modelowaniu satelitarnym Google Solar API i typowych polskich taryfach. Certyfikowany instalator po wizji lokalnej wyda wiążącą ofertę.",
    systemSize: "Rozmiar systemu",
    panel: "panel",
    panels: "paneli",
    max: "maks",
    adjustAssumptions: "Dostosuj założenia",
    electricityPrice: "Cena prądu",
    feedInPrice: "Cena odkupu",
    installCost: "Koszt instalacji",
    selfConsumption: "Autokonsumpcja",
    calculating: "Obliczanie…",
    annualProduction: "Roczna produkcja",
    kwhPerYear: "kWh/rok",
    yearOneSavings: "Oszczędności rok 1",
    systemCost: "Koszt systemu",
    payback: "Zwrot inwestycji",
    years: "lat",
    over25yr: "> 25 lat",
    lifetimeGain: "Zysk netto 25 lat",
    co2Offset: "Redukcja CO₂/rok",
  },
};

export const ptMarket: MarketConfig = {
  id: "pt",
  countryNameEn: "Portugal",
  countries: ["pt"],
  edition: "Edição Portugal",
  cities: "Lisboa · Porto · Faro · Coimbra",
  placeholder: "Rua Augusta 1, Lisboa…",
  solarDeclination: "DECLINAÇÃO SOLAR · 39°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.22,
    feedInPrice: 0.07,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.55,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "pt-PT",
  t: {
    kicker: "№ 01 — O seu mapa solar",
    headline1: "A quantidade de sol",
    headline2: "no seu telhado.",
    body: "Introduza um endereço português. Medimos o seu telhado por satélite, colocamos os painéis onde rendem mais e mostramos quanto poupa em vinte e cinco anos.",
    pressEnter: "Prima ↵ após selecionar a sugestão",
    trust1title: "Medição por satélite",
    trust1body: "Área, inclinação, orientação e sombreamento do telhado via Google Solar API.",
    trust2title: "Tarifas ERSE / UPAC",
    trust2body: "Preços de eletricidade, tarifa de injeção ERSE e custos de instalação em Portugal.",
    trust3title: "Instaladores certificados",
    trust3body: "Orçamentos de instaladores certificados DGEG, não de centros de atendimento.",
    property: "Propriedade",
    scanningRoof: "A analisar dados do telhado…",
    noData: "Sem dados disponíveis.",
    noCoverage: "Este endereço ainda não está coberto por dados solares por satélite. Experimente um endereço próximo.",
    tryAnother: "Tentar outro endereço",
    disclaimer: "As estimativas baseiam-se no modelo de satélite Google Solar API e nas tarifas portuguesas típicas. Um instalador certificado DGEG fornecerá um orçamento vinculativo após vistoria.",
    systemSize: "Tamanho do sistema",
    panel: "painel",
    panels: "painéis",
    max: "máx",
    adjustAssumptions: "Ajustar pressupostos",
    electricityPrice: "Preço da eletricidade",
    feedInPrice: "Tarifa de injeção",
    installCost: "Custo de instalação",
    selfConsumption: "Autoconsumo",
    calculating: "A calcular…",
    annualProduction: "Produção anual",
    kwhPerYear: "kWh / ano",
    yearOneSavings: "Poupança ano 1",
    systemCost: "Custo do sistema",
    payback: "Amortização",
    years: "anos",
    over25yr: "> 25 anos",
    lifetimeGain: "Ganho líquido 25 anos",
    co2Offset: "Redução CO₂ / ano",
  },
};

export const roMarket: MarketConfig = {
  id: "ro",
  countryNameEn: "Romania",
  countries: ["ro"],
  edition: "Ediția România",
  cities: "București · Cluj · Timișoara · Iași",
  placeholder: "Calea Victoriei 1, București…",
  solarDeclination: "DECLINAȚIE SOLARĂ · 45°N",
  currencySymbol: "lei",
  defaults: {
    electricityPrice: 0.70,
    feedInPrice: 0.15,
    installCostPerKwp: 5000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.10, max: 2.00, step: 0.05 },
    feedInPrice: { min: 0, max: 0.80, step: 0.02 },
    installCostPerKwp: { min: 2000, max: 5000, step: 200 },
  },
  locale: "ro-RO",
  t: {
    kicker: "№ 01 — Harta ta solară",
    headline1: "Cât soare primește",
    headline2: "acoperișul tău?",
    body: "Introduceți o adresă din România. Vom măsura acoperișul dvs. din satelit, vom plasa panourile acolo unde produc cel mai mult și vă vom arăta economiile în 25 de ani.",
    pressEnter: "Selectați adresa și apăsați ↵",
    trust1title: "Măsurare prin satelit",
    trust1body: "Suprafață, înclinare, orientare și umbrire acoperiș prin Google Solar API.",
    trust2title: "Tarife ANRE / prosumator",
    trust2body: "Prețuri curent ANRE, tarif prosumator de injecție în rețea și costuri de instalare în România.",
    trust3title: "Instalatori autorizați",
    trust3body: "Oferte de la instalatori autorizați ANRE pentru sisteme fotovoltaice.",
    property: "Proprietate",
    scanningRoof: "Se încarcă datele acoperișului…",
    noData: "Nu există date disponibile.",
    noCoverage: "Această adresă nu este acoperită de date solare prin satelit. Încercați o adresă apropiată.",
    tryAnother: "Încercați altă adresă",
    disclaimer: "Estimările se bazează pe modelarea prin satelit Google Solar API și pe tarifele tipice din România. Un instalator autorizat ANRE va furniza o ofertă fermă după vizita la fața locului.",
    systemSize: "Dimensiunea sistemului",
    panel: "panou",
    panels: "panouri",
    max: "max",
    adjustAssumptions: "Ajustați ipotezele",
    electricityPrice: "Prețul energiei",
    feedInPrice: "Tarif injecție",
    installCost: "Cost instalare",
    selfConsumption: "Autoconsum",
    calculating: "Se calculează…",
    annualProduction: "Producție anuală",
    kwhPerYear: "kWh/an",
    yearOneSavings: "Economii anul 1",
    systemCost: "Costul sistemului",
    payback: "Amortizare",
    years: "ani",
    over25yr: "> 25 ani",
    lifetimeGain: "Câștig net 25 ani",
    co2Offset: "Reducere CO₂/an",
  },
};

export const seMarket: MarketConfig = {
  id: "se",
  countryNameEn: "Sweden",
  countries: ["se"],
  edition: "Svensk utgåva",
  cities: "Stockholm · Göteborg · Malmö · Uppsala",
  placeholder: "Drottninggatan 1, Stockholm…",
  solarDeclination: "SOLARDEKLINASJON · 59°N",
  currencySymbol: "kr",
  defaults: {
    electricityPrice: 2.20,
    feedInPrice: 0.50,
    installCostPerKwp: 11000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.50, max: 5.00, step: 0.10 },
    feedInPrice: { min: 0, max: 2.00, step: 0.05 },
    installCostPerKwp: { min: 5000, max: 12000, step: 500 },
  },
  locale: "sv-SE",
  t: {
    kicker: "№ 01 — Din solkarta",
    headline1: "Hur mycket sol",
    headline2: "får ditt tak?",
    body: "Ange en svensk adress. Vi mäter ditt tak från satellit, placerar paneler där de ger mest avkastning och visar dina besparingar över tjugofem år.",
    pressEnter: "Välj ett förslag och tryck ↵",
    trust1title: "Satellitmätning",
    trust1body: "Takarea, lutning, orientering och skuggning via Google Solar API.",
    trust2title: "Skattereduktion & elcertifikat",
    trust2body: "Aktuella elpriser, skattereduktion för mikroproduktion och installationskostnader i Sverige.",
    trust3title: "Certifierade installatörer",
    trust3body: "Offerter från Elsäkerhetsverket-certifierade solcellsinstallatörer, inga callcenter.",
    property: "Fastighet",
    scanningRoof: "Laddar takdata…",
    noData: "Inga data tillgängliga.",
    noCoverage: "Den här adressen täcks inte av satellitbaserad soldata ännu. Prova en adress i närheten.",
    tryAnother: "Prova en annan adress",
    disclaimer: "Uppskattningarna baseras på Google Solar API satellit­modellering och typiska svenska tariffer. En certifierad installatör ger ett bindande anbud efter besiktning.",
    systemSize: "Systemstorlek",
    panel: "panel",
    panels: "paneler",
    max: "max",
    adjustAssumptions: "Justera antaganden",
    electricityPrice: "Elpris",
    feedInPrice: "Inmatningspris",
    installCost: "Installationskostnad",
    selfConsumption: "Egenförbrukning",
    calculating: "Beräknar…",
    annualProduction: "Årsproduktion",
    kwhPerYear: "kWh/år",
    yearOneSavings: "Besparingar år 1",
    systemCost: "Systemkostnad",
    payback: "Återbetalningstid",
    years: "år",
    over25yr: "> 25 år",
    lifetimeGain: "Nettovinst 25 år",
    co2Offset: "CO₂-minskning/år",
  },
};

export const siMarket: MarketConfig = {
  id: "si",
  countryNameEn: "Slovenia",
  countries: ["si"],
  edition: "Slovenska izdaja",
  cities: "Ljubljana · Maribor · Celje · Kranj",
  placeholder: "Slovenska cesta 1, Ljubljana…",
  solarDeclination: "SONČEVA DEKLINACIJA · 46°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.18,
    feedInPrice: 0.06,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "sl-SI",
  t: {
    kicker: "№ 01 — Vaš sončni zemljevid",
    headline1: "Koliko sonca ima",
    headline2: "vaša streha?",
    body: "Vnesite slovenski naslov. Izmerili bomo vašo streho s satelita, postavili panele tja, kjer prinesejo največ, in vam pokazali prihranke v petindvajsetih letih.",
    pressEnter: "Izberite naslov in pritisnite ↵",
    trust1title: "Satelitska meritev",
    trust1body: "Površina strehe, naklon, orientacija in senčenje prek Google Solar API.",
    trust2title: "Slovenski OVE tarifit",
    trust2body: "Aktualne cene električne energije, odkupna cena OVE AGEN-RS in stroški namestitve v Sloveniji.",
    trust3title: "Certificirani inštalaterji",
    trust3body: "Ponudbe od certificiranih inštalaterjev fotovoltaičnih sistemov v Sloveniji.",
    property: "Nepremičnina",
    scanningRoof: "Nalaganje podatkov o strehi…",
    noData: "Ni razpoložljivih podatkov.",
    noCoverage: "Ta naslov še ni pokrit s satelitskimi solarnimi podatki. Poskusite z bližnjim naslovom.",
    tryAnother: "Poskusite z drugim naslovom",
    disclaimer: "Ocene temeljijo na satelitskem modeliranju Google Solar API in tipičnih slovenskih tarifah. Certificiran inštalater bo po ogledu na terenu podal zavezujočo ponudbo.",
    systemSize: "Velikost sistema",
    panel: "panel",
    panels: "panelov",
    max: "maks",
    adjustAssumptions: "Prilagodi predpostavke",
    electricityPrice: "Cena električne energije",
    feedInPrice: "Odkupna cena",
    installCost: "Stroški namestitve",
    selfConsumption: "Samoporaba",
    calculating: "Računanje…",
    annualProduction: "Letna proizvodnja",
    kwhPerYear: "kWh/leto",
    yearOneSavings: "Prihranki leto 1",
    systemCost: "Cena sistema",
    payback: "Povrnitev investicije",
    years: "let",
    over25yr: "> 25 let",
    lifetimeGain: "Neto dobiček 25 let",
    co2Offset: "Zmanjšanje CO₂/leto",
  },
};

export const skMarket: MarketConfig = {
  id: "sk",
  countryNameEn: "Slovakia",
  countries: ["sk"],
  edition: "Slovenské vydanie",
  cities: "Bratislava · Košice · Prešov · Nitra",
  placeholder: "Obchodná ulica 1, Bratislava…",
  solarDeclination: "SLNEČNÁ DEKLINÁCIA · 48°N",
  currencySymbol: "€",
  defaults: {
    electricityPrice: 0.20,
    feedInPrice: 0.06,
    installCostPerKwp: 1000,
    selfConsumptionRatio: 0.50,
  },
  ranges: {
    electricityPrice: { min: 0.05, max: 0.60, step: 0.01 },
    feedInPrice: { min: 0, max: 0.30, step: 0.01 },
    installCostPerKwp: { min: 400, max: 1000, step: 50 },
  },
  locale: "sk-SK",
  t: {
    kicker: "№ 01 — Vaša slnečná mapa",
    headline1: "Koľko slnka dopadá",
    headline2: "na vašu strechu?",
    body: "Zadajte slovenský adresár. Zmeráme vašu strechu zo satelitu, umiestníme panely tam, kde zarobia najviac, a ukážeme vám úspory za dvadsaťpäť rokov.",
    pressEnter: "Vyberte adresu a stlačte ↵",
    trust1title: "Satelitné meranie",
    trust1body: "Plocha strechy, sklon, orientácia a zatienenie cez Google Solar API.",
    trust2title: "URSO tarify / FiT",
    trust2body: "Aktuálne ceny elektriny, výkupná cena URSO a náklady na inštaláciu na Slovensku.",
    trust3title: "Certifikovaní inštalatéri",
    trust3body: "Ponuky od certifikovaných inštalatérov fotovoltaických systémov na Slovensku.",
    property: "Nehnuteľnosť",
    scanningRoof: "Načítanie dát strechy…",
    noData: "Žiadne údaje nie sú k dispozícii.",
    noCoverage: "Táto adresa zatiaľ nie je pokrytá satelitnými slnečnými dátami. Skúste blízku adresu.",
    tryAnother: "Skúste inú adresu",
    disclaimer: "Odhady sú založené na Google Solar API a typických slovenských tarifách. Certifikovaný inštalatér poskytne záväznú ponuku po miestnej obhliadke.",
    systemSize: "Veľkosť systému",
    panel: "panel",
    panels: "panelov",
    max: "max",
    adjustAssumptions: "Upraviť predpoklady",
    electricityPrice: "Cena elektriny",
    feedInPrice: "Výkupná cena",
    installCost: "Náklady na inštaláciu",
    selfConsumption: "Vlastná spotreba",
    calculating: "Výpočet…",
    annualProduction: "Ročná výroba",
    kwhPerYear: "kWh/rok",
    yearOneSavings: "Úspory rok 1",
    systemCost: "Cena systému",
    payback: "Návratnosť",
    years: "rokov",
    over25yr: "> 25 rokov",
    lifetimeGain: "Čistý zisk 25 rokov",
    co2Offset: "Úspora CO₂/rok",
  },
};

export const nordicMarket: MarketConfig = fiMarket;
export const dachMarket: MarketConfig = deMarket;
export const ukMarket: MarketConfig = gbMarket;
